### ISSUE TITLE
Finalizing v0.4

### ISSUE THREAD

**Issue by constantinpape** [ome/ngff#86]
- [ ] MUST DO
  - [x] Finalize axes & transformations #85 
  - [x] Update the example data (e.g. in https://github.com/ome/ome-ngff-prototypes) for changes in #85 
  - [ ] Finalize support in ome-zarr-py/ome-zarr-napari, vizarr and BDV/MoBIE
  - [x] Updates to the HCS spec (cc @sbesson; I am not sure what the current status or related PR is)
  - [x] jsonschema for v0.4 #82
- [ ] CAN DO
  - [ ] top level version information #83 
  - [x] specify zarr version #80 PR: #88
  - [ ] specify encoding in json #81
- [ ] POST-RELEASE: write up a quick summary about how to contribute a spec extension (PR & release process)

Decided to push to next release:
  - Origin definition #89, see https://github.com/ome/ngff/issues/89#issuecomment-1027692519
  
Timeline: I will work on this next week during the hackathon and hope that we can release in the next 2 weeks or so.

**Comment by sbesson** [comment]
@constantinpape for the HCS point, I'll review the recording of the evening session for the 6th NGFFcommunity call as I missed it. In the absence of vetoes, the next step will be to merge https://github.com/ome/ngff/pull/24

**Comment by constantinpape** [comment]
See also https://github.com/ome/ome-ngff-prototypes/pull/2 for updating the example data

**Comment by constantinpape** [comment]
I have updated the example data now, see https://github.com/ome/ome-ngff-prototypes#data-availability.
So now the only important thing left to do is to get the viewers up to speed ... I will ping the MoBIE side about this.

How's the progress on this in python/napari and vizarr, @sbesson @will-moore?

And do you still want to merge #92 before we release @sbesson? I would suggest to leave the other open points for the next minor release, or an intermediate patch release.

**Comment by constantinpape** [comment]
I just found this old issue, which is still relevant: https://github.com/ome/ngff/issues/2
A good candidate for a patch release. (Just linking it here for visibility)

**Comment by sbesson** [comment]
> And do you still want to merge https://github.com/ome/ngff/pull/92 before we release @sbesson?

Although I suspect this particular PR might be merged soon, I would not consider this as a blocker for  the specification release and rather mark it as a CAN DO item. Overall, there is still some work to perform on these JSON schemas including improving the checks in the strict image schemas (units), adding schemas for other specifications (plate, well). I suspect this will be broken out into PRs/issues and continue after the 0.4.0 release.

**Comment by sbesson** [comment]
https://ngff.openmicroscopy.org/0.4/ is now live 🎉

**Comment by constantinpape** [comment]
Thanks @sbesson. I will follow up here later today.

**Comment by constantinpape** [comment]
Hey @sbesson @will-moore @joshmoore,
just a quick follow-up on this from my side: we can read v0.4 in MoBIE now and are still working on writing it. Will hopefully be finished this week and then we will make a new release that fully supports 0.4. (I tentatively marked MoBIE as done now;))
How is the progress on support in napari/vizarr?

I have also moved the minor points to #100, since this will not be part of 0.4.

**Comment by will-moore** [comment]
PR for 0.4 support in napari is merged (https://github.com/ome/napari-ome-zarr/pull/32), but we still need to release.
Vizarr is done, but that only involved the handling of axis names since it doesn't support scalebar or transformations yet.
